import type { Metadata } from "next";
import "./globals.css";
import { ChakraProvider } from "@chakra-ui/react";

import { Providers } from './provider'

export const metadata: Metadata = {
  title: "Landing Page",
  description: "Generated by Kamana",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body >
        <Providers>{children}</Providers>
        </body>
     </html>
  );
}
